# üèè TerpCricket Database üìä <img src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExeTZ3djhqdjJ5NmZyZjg3ZHV2cDl5NzRrOGw1ZGR1ZXFzc29xd3RrdSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/Rt53HzeMVFGKgpc19h/giphy.gif" width="100">

<p align="center">
  <img src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWdvM3RiN2czZnVhdHE2aXh5Y2w2ZG1kaG4xcTIzdjdmMjQ4YThpNiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Xq6fo6kkvIZr3L7pCn/giphy.gif" width="500">
</p>

**Imaginary Business Idea:**

**TerpCricket - Bringing Cricket to Maryland and D.C.**

So what is TerpCricket?

TerpCricket is a speciality retail store that is dedicated purely to cricket.

If you were wondering, "Cricket is a bat-and-ball team sport played on an oval-shaped field. Two teams of 11 players take turns batting and fielding. The goal of the batting side is to score runs by running between the wickets, while the bowling side tries to get the batters out" [(Google AI)](https://www.google.com/search?q=what+is+cricket&rlz=1C5CHFA_enIN1084IN1084&oq=what+is+cricket&gs_lcrp=EgZjaHJvbWUyEQgAEEUYFBg5GIcCGLEDGIAEMgcIARAAGIAEMgcIAhAAGIAEMgcIAxAAGIAEMgcIBBAAGIAEMgcIBRAAGIAEMgcIBhAAGIAEMgcIBxAAGIAEMgcICBAAGIAEMgcICRAAGIAE0gEIMTgyM2owajeoAgCwAgA&sourceid=chrome&ie=UTF-8).

Anyways, this retail store is located on the University of Maryland, College Park campus, which is close to all of Maryland and D.C.

The store will sell high-quality bats, balls, pads, gloves, jerseys, and other cricket essentials which also offering services such as equipment rental, repairs, and possible coaching sessions in the future.

# **Entity Definitions for TerpCricket**

## **1) Customers**  
Customers are cricket enthusiasts from all over **D.C. and Maryland** who visit **College Park** to find quality cricket equipment that is otherwise unavailable in most other stores. Given the growing **South Asian and international student population**, there is a strong demand for cricket gear, and TerpCricket is uniquely positioned to serve this niche market.

### **Attributes**
| Column Name   | Data Type       | Description                         |
|--------------|----------------|-------------------------------------|
| **customer_id**  | `INT PRIMARY KEY AUTO_INCREMENT` | Unique identifier for each customer |
| first_name   | `VARCHAR(50)`   | Customer's first name              |
| last_name    | `VARCHAR(50)`   | Customer's last name               |
| email        | `VARCHAR(100) UNIQUE` | Customer's email address |
| phone_number | `VARCHAR(15)`   | Customer's phone number            |
| join_date    | `DATE`          | Date when the customer signed up   |

---

## **2) Orders**  
Orders represent **transactions made by customers** when purchasing cricket equipment. Each order includes details such as the **customer placing the order, the date of purchase, the total cost, and the employee handling the sale**. Since cricket equipment varies widely in price, from affordable practice gear to premium customized bats, orders can range from small purchases to bulk team orders for tournaments. Additionally, TerpCricket may introduce **pre-orders for exclusive cricket kits** and allow customers to request special equipment.

### **Attributes**
| Column Name   | Data Type       | Description                          |
|--------------|----------------|--------------------------------------|
| **order_id**     | `INT PRIMARY KEY AUTO_INCREMENT` | Unique order identifier |
| customer_id  | `INT`           | Foreign Key referencing Customers (`customer_id`) |
| employee_id  | `INT`           | Foreign Key referencing Employees (`employee_id`) |
| order_date   | `DATETIME`      | Date and time when the order was placed |
| total_amount | `DECIMAL(10,2)` | Total price of the order |

---

## **3) Products**  
TerpCricket offers a **wide range of high-quality cricket equipment**, from **protective gloves, bats, and helmets** to **imported cricket balls and tailored gear** designed to meet the specific needs of players. Our inventory includes both **professional and beginner-friendly options**, ensuring that every cricket enthusiast‚Äîfrom casual backyard players to competitive league athletes‚Äîcan find the perfect fit. We also provide **customized jerseys** for teams and individuals looking to represent their cricket passion.

### **Attributes**
| Column Name   | Data Type       | Description                          |
|--------------|----------------|--------------------------------------|
| **product_id**   | `INT PRIMARY KEY AUTO_INCREMENT` | Unique identifier for each product |
| name         | `VARCHAR(100)`  | Product name (e.g., "Cricket Bat")  |
| category     | `VARCHAR(50)`   | Product category (e.g., "Bat", "Ball", "Gloves") |
| price        | `DECIMAL(10,2)` | Price of the product                |
| stock        | `INT`           | Number of items in stock            |
| supplier_id  | `INT`           | Foreign Key referencing Suppliers (`supplier_id`) |

---

## **4) Order_Items**  
The **Order_Items** entity manages the **individual products purchased within an order**. Since customers often **buy multiple products at once**, this table ensures that each order can contain **various items in different quantities**. It allows for tracking of each product‚Äôs **stock levels, pricing at the time of sale, and total cost per product category** within an order. Additionally, it helps with analyzing **popular product trends** to optimize future inventory decisions.

### **Attributes**
| Column Name   | Data Type       | Description                          |
|--------------|----------------|--------------------------------------|
| **order_item_id** | `INT PRIMARY KEY AUTO_INCREMENT` | Unique ID for the order item |
| order_id     | `INT`           | Foreign Key referencing Orders (`order_id`) |
| product_id   | `INT`           | Foreign Key referencing Products (`product_id`) |
| quantity     | `INT`           | Number of units purchased |
| subtotal     | `DECIMAL(10,2)` | Price for this product in the order |

---

## **5) Employees**  
TerpCricket is **entirely student-run**, making it a **unique business initiative led by students for students**. Every aspect of the store‚Äîfrom sales and marketing to operations and logistics‚Äîis managed by passionate students looking to promote cricket in the U.S. This initiative not only supports the **growth of the sport** but also **creates valuable employment opportunities** for students at the University of Maryland. By working at TerpCricket, students gain **business experience, customer service skills, and leadership opportunities** while fostering a **strong cricket community** on campus. Moreover, this initiative could encourage **more students to get involved in cricket**, whether as players, coaches, or future entrepreneurs in the sports industry.

### **Attributes**
| Column Name   | Data Type       | Description                          |
|--------------|----------------|--------------------------------------|
| **employee_id**  | `INT PRIMARY KEY AUTO_INCREMENT` | Unique employee ID |
| first_name   | `VARCHAR(50)`   | Employee's first name |
| last_name    | `VARCHAR(50)`   | Employee's last name |
| email        | `VARCHAR(100) UNIQUE` | Employee's email |
| phone_number | `VARCHAR(15)`   | Contact number |
| role         | `VARCHAR(50)`   | Role (e.g., "Sales Rep", "Manager") |
| salary       | `DECIMAL(10,2)` | Monthly salary |

---

## **6) Suppliers**  
We have partnered with **exclusive and highly reputed suppliers from India** who are dedicated to expanding cricket in countries where the sport is still developing. These suppliers provide **top-tier cricket gear, ensuring authenticity and quality**. Additionally, we collaborate with **Indian stores in the U.S., such as Patel Brothers**, to facilitate easier importation and distribution of cricket products. This ensures that our customers have **access to premium equipment** without long international shipping delays. By working with suppliers focused on **global cricket development**, we ensure that players in the U.S. can experience the same level of quality as professionals in cricket-dominant nations.

### **Attributes**
| Column Name   | Data Type       | Description                          |
|--------------|----------------|--------------------------------------|
| **supplier_id** | `INT PRIMARY KEY AUTO_INCREMENT` | Unique supplier ID |
| name         | `VARCHAR(100)`  | Supplier name |
| contact_name | `VARCHAR(100)`  | Contact person's name |
| phone_number | `VARCHAR(15)`   | Supplier's phone number |
| email        | `VARCHAR(100) UNIQUE` | Contact email |
| address      | `VARCHAR(255)`  | Supplier's address |

# **Relationships Between Entities in TerpCricket**

## **1) Customers (1:M) Orders**
- **One customer** can place **multiple orders**.
- **Each order** belongs to only **one customer**.
- This relationship ensures that we can track all purchases made by a specific customer.

**Foreign Key:** `Orders.customer_id ‚Üí Customers.customer_id`

---

## **2) Orders (1:M) Order_Items**
- **One order** can contain **multiple products**.
- **Each entry in Order_Items** represents a **product purchased in an order**.
- This allows us to track the **quantity and subtotal** for each product within an order.

**Foreign Key:** `Order_Items.order_id ‚Üí Orders.order_id`

---

## **3) Products (1:M) Order_Items**
- **One product** can be purchased in **multiple orders**.
- **Each entry in Order_Items** links a **product to a specific order**.
- This ensures that we can analyze product sales performance.

**Foreign Key:** `Order_Items.product_id ‚Üí Products.product_id`

---

## **4) Orders (M:1) Employees**
- **Each order** is processed by **one employee**.
- **One employee** can handle **multiple orders**.
- This ensures that employee productivity and order management can be tracked.

**Foreign Key:** `Orders.employee_id ‚Üí Employees.employee_id`

---

## **5) Products (M:1) Suppliers**
- **One supplier** can provide **multiple products**.
- **Each product** is sourced from **one supplier**.
- This ensures we can track where each product is coming from.

**Foreign Key:** `Products.supplier_id ‚Üí Suppliers.supplier_id`

---

## **Summary of Relationships**
| **Relationship**  | **Cardinality** | **Description** |
|------------------|---------------|----------------|
| **Customers ‚Üî Orders** | 1:M | One customer can place multiple orders. |
| **Orders ‚Üî Order_Items** | 1:M | One order can contain multiple products. |
| **Products ‚Üî Order_Items** | 1:M | One product can appear in multiple orders. |
| **Orders ‚Üî Employees** | M:1 | One employee processes multiple orders. |
| **Products ‚Üî Suppliers** | M:1 | One supplier provides multiple products. |

## ENTITY RELATIONSHIP DIAGRAM

![ER1.png]()

#**Normalization of TerpCricket's Relational Database Schema**

## **First Normal Form**


*   All columns contain atomic values [no lists or mulitple values in a single field ].
*   Each row has a unique identifier [ Primary Key ].
*   No duplicate Rows.

Since all our tables have a primary key, and all of our attributes contain atomic values and no duplicate rows, it satisfies First Normal Form

## **Second Normal Form**

*   Must be in First Normal Form.
*   Must not contain partial dependencies [ i.e. all non-key columns must depend on the entire primary key, and not just a part of it ].

Since our tables with single-column primary keys, every column fully depends no the Primary Key, and no column is partially depended on just one part of a composite key[ even Order_Items table which has order_id and product_id as a composite primary key, all the attributes fully depend on both of these keys ], it satisfies the Second normal form.

## **Third Normal Form**

*   Must satisfy Second Normal Form.
*   Must have non transitive dependencies [ A non key column must depend only on primary key and not any other non key column itself ]

Since our tables follow these and have no unnecessary dependencies either, our whole database follows **Third Normal Form**

In [36]:
import sqlite3
import pandas as pd
import numpy as np

In [37]:
con = sqlite3.connect("TerpCricket.db")

Since we are on Colab, the SQLite database "TerpCricket.db" will be created in a temporary runtime environment, in our root directory. It will be located at '/content/TerpCricket.db'

In [4]:
cur = con.cursor()

In [8]:
!ls /content

sample_data  TerpCricket.db

As we can see, it is inside '/content'

Now, in order to store and modify databases directly, let us create the database from our google drive itself. basically, we will set up our SQLite server inside our Google Drive.

In [57]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [59]:
db_path = "/content/drive/MyDrive/TerpCricket.db"
con = sqlite3.connect(db_path)
cur = con.cursor()

In [40]:
!ls /content/drive/MyDrive

'2024 Fall GX Application.docx'
'2024 Fall GX job descriptions.docx'
'Analysis Report: Books Related to Sex Education, LGBTQ+, and Other Related Topics.gdoc'
'Book Records.gsheet'
'Colab Notebooks'
'Essay1 final.docx'
 Essay1.gdoc
 Essay2.gdoc
'Meeting Reports'
 MSML602-Project0.gdoc
'Pramod Kumar - DATA604 - Assignment 1.gdoc'
 Pramod-Kumar-Resume.pdf
 PramodKumar_Resume.pdf
'requested books.gsheet'
'shoemaker - keys check original version.gsheet'
 TerpCricket.db
'Testudo - Schedule.pdf'
'Untitled document.gdoc'
'Untitled spreadsheet.gsheet'

In [60]:
# Define table creation queries
table_queries = {
    "Customers": """
    CREATE TABLE IF NOT EXISTS Customers (
        customer_id INTEGER PRIMARY KEY AUTOINCREMENT,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        phone_number TEXT NOT NULL,
        join_date DATE NOT NULL
    );
    """,

    "Products": """
    CREATE TABLE IF NOT EXISTS Products (
        product_id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        price REAL NOT NULL,
        stock INTEGER NOT NULL,
        supplier_id INTEGER NOT NULL,
        FOREIGN KEY (supplier_id) REFERENCES Suppliers(supplier_id)
    );
    """,

    "Orders": """
    CREATE TABLE IF NOT EXISTS Orders (
        order_id INTEGER PRIMARY KEY AUTOINCREMENT,
        customer_id INTEGER NOT NULL,
        employee_id INTEGER NOT NULL,
        order_date DATETIME NOT NULL,
        total_amount REAL NOT NULL,
        FOREIGN KEY (customer_id) REFERENCES Customers(customer_id),
        FOREIGN KEY (employee_id) REFERENCES Employees(employee_id)
    );
    """,

    "Order_Items": """
    CREATE TABLE IF NOT EXISTS Order_Items (
        order_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
        order_id INTEGER NOT NULL,
        product_id INTEGER NOT NULL,
        quantity INTEGER NOT NULL,
        subtotal REAL NOT NULL,
        FOREIGN KEY (order_id) REFERENCES Orders(order_id),
        FOREIGN KEY (product_id) REFERENCES Products(product_id)
    );
    """,

    "Employees": """
    CREATE TABLE IF NOT EXISTS Employees (
        employee_id INTEGER PRIMARY KEY AUTOINCREMENT,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        phone_number TEXT NOT NULL,
        role TEXT NOT NULL,
        salary REAL NOT NULL
    );
    """,

    "Suppliers": """
    CREATE TABLE IF NOT EXISTS Suppliers (
        supplier_id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        contact_name TEXT NOT NULL,
        phone_number TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        address TEXT NOT NULL
    );
    """
}

# Execute table creation queries
for table, query in table_queries.items():
    cur.execute(query)

# Commit changes
con.commit()
print("All tables created successfully!")

All tables created successfully!

In [61]:
cur.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables_created = cur.fetchall()
print("Tables in the database:", tables_created)

Tables in the database: [('Customers',), ('sqlite_sequence',), ('Products',), ('Orders',), ('Order_Items',), ('Employees',), ('Suppliers',)]

In [62]:
# Reconnect to the database
con = sqlite3.connect(db_path)
cur = con.cursor()

# Get all table names
cur.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cur.fetchall()

# Print schema details for each table
print("\nDatabase Schema:")
for table in tables:
    table_name = table[0]
    print(f"\nüü¢ Table: {table_name}")

    # Get column details
    cur.execute(f"PRAGMA table_info({table_name});")
    columns = cur.fetchall()

    # Print column details
    print("{:<5} {:<20} {:<15} {}".format("ID", "Column Name", "Data Type", "Constraints"))
    print("-" * 50)

    for col in columns:
        col_id, col_name, col_type, not_null, default_val, pk = col
        constraints = []
        if pk:
            constraints.append("PRIMARY KEY")
        if not_null:
            constraints.append("NOT NULL")
        print(f"{col_id:<5} {col_name:<20} {col_type:<15} {' '.join(constraints)}")

# Close connection
con.close()

Database Schema:

üü¢ Table: Customers
ID    Column Name          Data Type       Constraints
--------------------------------------------------
0     customer_id          INTEGER         PRIMARY KEY
1     first_name           TEXT            NOT NULL
2     last_name            TEXT            NOT NULL
3     email                TEXT            NOT NULL
4     phone_number         TEXT            NOT NULL
5     join_date            DATE            NOT NULL

üü¢ Table: sqlite_sequence
ID    Column Name          Data Type       Constraints
--------------------------------------------------
0     name
1     seq

üü¢ Table: Products
ID    Column Name          Data Type       Constraints
--------------------------------------------------
0     product_id           INTEGER         PRIMARY KEY
1     name                 TEXT            NOT NULL
2     category             TEXT            NOT NULL
3     price                REAL            NOT NULL
4     stock                INTEGER         NOT NULL
5     supplier_id          INTEGER         NOT NULL

üü¢ Table: Orders
ID    Column Name          Data Type       Constraints
--------------------------------------------------
0     order_id             INTEGER         PRIMARY KEY
1     customer_id          INTEGER         NOT NULL
2     employee_id          INTEGER         NOT NULL
3     order_date           DATETIME        NOT NULL
4     total_amount         REAL            NOT NULL

üü¢ Table: Order_Items
ID    Column Name          Data Type       Constraints
--------------------------------------------------
0     order_item_id        INTEGER         PRIMARY KEY
1     order_id             INTEGER         NOT NULL
2     product_id           INTEGER         NOT NULL
3     quantity             INTEGER         NOT NULL
4     subtotal             REAL            NOT NULL

üü¢ Table: Employees
ID    Column Name          Data Type       Constraints
--------------------------------------------------
0     employee_id          INTEGER         PRIMARY KEY
1     first_name           TEXT            NOT NULL
2     last_name            TEXT            NOT NULL
3     email                TEXT            NOT NULL
4     phone_number         TEXT            NOT NULL
5     role                 TEXT            NOT NULL
6     salary               REAL            NOT NULL

üü¢ Table: Suppliers
ID    Column Name          Data Type       Constraints
--------------------------------------------------
0     supplier_id          INTEGER         PRIMARY KEY
1     name                 TEXT            NOT NULL
2     contact_name         TEXT            NOT NULL
3     phone_number         TEXT            NOT NULL
4     email                TEXT            NOT NULL
5     address              TEXT            NOT NULL

In [63]:
# Connect to the SQLite database
con = sqlite3.connect(db_path)
cur = con.cursor()

# Inserting data into the Customers table (auto-generating IDs)
cur.executemany("""
    INSERT INTO Customers (first_name, last_name, email, phone_number, join_date)
    VALUES (?, ?, ?, ?, ?);
""", [
    ("Sachin", "Tendulkar", "sachintd@gmail.com", "123-456-7890", "2025-01-01"),
    ("MS", "Dhoni", "mahi7@gmail.com", "234-567-8901", "2025-01-02"),
    ("Aaron", "Jones", "aaronjones@umd.edu", "345-678-9012", "2025-01-03"),
    ("Virat", "Kohli", "viratkohli@hotmail.com", "456-789-0123", "2025-01-04"),
    ("Lebron", "James", "kinglebron@nba.us", "567-890-1234", "2025-01-05"),
    ("Kevin", "Durrant", "kd7@nba.com", "678-901-2345", "2025-01-06"),
    ("Steven", "Smith", "ssmith@cricketaus.com", "789-012-3456", "2025-01-07"),
    ("Tai", "Felton", "tfelton@umd.edu", "890-123-4567", "2025-01-08"),
    ("Julian", "Reece", "julianreece@umd.edu", "901-234-5678", "2025-01-09"),
    ("Saylor", "Poffenbarger", "poffenbarger@umd.edu", "012-345-6789", "2025-01-10")
])

# Insert data into the Suppliers table
cur.executemany("""
    INSERT INTO Suppliers (name, contact_name, phone_number, email, address)
    VALUES (?, ?, ?, ?, ?);
""", [
    ("Decathlon", "Rajesh Kumar", "111-222-3333", "raj@indiacricket.com", "Mumbai, India"),
    ("Global Sports", "Eoin Morgan", "222-333-4444", "morgan@globalsports.com", "Los Angeles, USA"),
    ("ProCricket", "Arvind Patel", "333-444-5555", "arvind@procricket.com", "Delhi, India"),
    ("Chennai Sports Hub", "Nirav Patel", "444-555-6666", "nirav@patelbros.com", "Chennai, India"),
    ("SportyTech", "Mike Johnson", "555-666-7777", "mike@sportytech.com", "New York, USA"),
    ("Ultimate Cricket", "Rahul Sharma", "666-777-8888", "rahul@ultimatecricket.com", "Hyderabad, India"),
    ("Cricket Universe", "Jessica White", "777-888-9999", "jessica@cricketuniverse.com", "London, UK"),
    ("Elite Cricket Store", "Tom Carter", "888-999-0000", "tom@elitecricket.com", "Sydney, Australia"),
    ("ProSports", "Daniel Green", "999-000-1111", "daniel@prosports.com", "San Francisco, USA"),
    ("MasterCricket", "Vikram Singh", "000-111-2222", "vikram@mastercricket.com", "Bangalore, India")
])

# Insert data into the Products table
cur.executemany("""
    INSERT INTO Products (name, category, price, stock, supplier_id)
    VALUES (?, ?, ?, ?, ?);
""", [
    ("Cricket Bat", "Bat", 120.00, 50, 1),
    ("Cricket Ball", "Ball", 15.00, 200, 2),
    ("Gloves", "Protective Gear", 45.00, 100, 3),
    ("Helmet", "Protective Gear", 75.00, 80, 4),
    ("Cricket Pads", "Protective Gear", 60.00, 90, 5),
    ("Wicket Keeper Gloves", "Protective Gear", 50.00, 70, 6),
    ("Cricket Stumps", "Accessories", 40.00, 60, 7),
    ("Cricket Jersey", "Apparel", 30.00, 150, 8),
    ("Cricket Shoes", "Footwear", 85.00, 120, 9),
    ("Cricket Kit Bag", "Accessories", 55.00, 130, 10)
])

# Insert data into the Employees' table
cur.executemany("""
    INSERT INTO Employees (first_name, last_name, email, phone_number, role, salary)
    VALUES (?, ?, ?, ?, ?, ?);
""", [
    ("Pramod", "Kumar", "pramod21@terpcricket.com", "123-111-2222", "Manager", 50000.00),
    ("Swati", "Nair", "swati@terpcricket.com", "234-222-3333", "Sales Rep", 35000.00),
    ("Anirudh", "Jayaprakash", "ajp@terpcricket.com", "345-333-4444", "Sales Rep", 36000.00),
    ("Bruce ", "Wayne Jr.", "batman@terpcricket.com", "456-444-5555", "Inventory Manager", 40000.00),
    ("Peter", "Parker", "spideyterp@terpcricket.com", "567-555-6666", "Cashier", 30000.00),
    ("Taylor", "Swift", "ts@terpcricket.com", "678-666-7777", "Customer Support", 32000.00),
    ("Ryan", "Howard", "ryan@terpcricket.com", "789-777-8888", "Marketing", 33000.00),
    ("Angela", "Martin", "angela@terpcricket.com", "890-888-9999", "Accountant", 37000.00),
    ("Anirud", "Mohan", "am@terpcricket.com", "901-999-0000", "Finance", 38000.00),
    ("Tammy", "Perin", "tammy@terpcricket.com", "012-000-1111", "HR", 34000.00)
])

# Insert data into the Orders table
cur.executemany("""
    INSERT INTO Orders (customer_id, employee_id, order_date, total_amount)
    VALUES (?, ?, ?, ?);
""", [
    (1, 2, "2025-02-10 14:30:00", 135.00),
    (2, 3, "2025-02-11 15:45:00", 180.00),
    (3, 4, "2025-02-12 16:00:00", 90.00),
    (4, 5, "2025-02-13 17:30:00", 75.00),
    (5, 1, "2025-02-14 18:00:00", 120.00),
    (6, 6, "2025-02-15 12:00:00", 200.00),
    (7, 7, "2025-02-16 13:45:00", 250.00),
    (8, 8, "2025-02-17 14:30:00", 300.00),
    (9, 9, "2025-02-18 15:15:00", 150.00),
    (10, 10, "2025-02-19 16:00:00", 220.00)
])

# Insert data into the Order_Items table
cur.executemany("""
    INSERT INTO Order_Items (order_id, product_id, quantity, subtotal)
    VALUES (?, ?, ?, ?);
""", [
    (1, 1, 2, 240.00),
    (1, 3, 1, 45.00),
    (2, 2, 5, 75.00),
    (2, 4, 1, 75.00),
    (3, 5, 1, 60.00),
    (4, 6, 2, 100.00),
    (5, 7, 1, 40.00),
    (6, 8, 3, 90.00),
    (7, 9, 2, 170.00),
    (8, 10, 1, 55.00),
    (9, 2, 3, 45.00),
    (10, 4, 2, 150.00)
])


# Commit the changes
con.commit()

In [64]:
con = sqlite3.connect(db_path)
cur = con.cursor()

# Fetch all table names
cur.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cur.fetchall()

# Print table names
print("Tables in the database:")
for table in tables:
    print("-", table[0])

Tables in the database:
- Customers
- sqlite_sequence
- Products
- Orders
- Order_Items
- Employees
- Suppliers

In [65]:
from IPython.display import display

# Connect to the SQLite database
con = sqlite3.connect(db_path)
cur = con.cursor()

# Fetch all table names
cur.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cur.fetchall()

# Loop through each table and display it nicely
for table in tables:
    table_name = table[0]
    print(f"\nüîπ Table: {table_name}")

    # Fetch table data
    df = pd.read_sql_query(f"SELECT * FROM {table_name}", con)

    # Display as a properly formatted table in Colab
    display(df)

üîπ Table: Customers

,customer_id,first_name,last_name,email,phone_number,join_date
0,1,Sachin,Tendulkar,sachintd@gmail.com,123-456-7890,2025-01-01
1,2,MS,Dhoni,mahi7@gmail.com,234-567-8901,2025-01-02
2,3,Aaron,Jones,aaronjones@umd.edu,345-678-9012,2025-01-03
3,4,Virat,Kohli,viratkohli@hotmail.com,456-789-0123,2025-01-04
4,5,Lebron,James,kinglebron@nba.us,567-890-1234,2025-01-05
5,6,Kevin,Durrant,kd7@nba.com,678-901-2345,2025-01-06
6,7,Steven,Smith,ssmith@cricketaus.com,789-012-3456,2025-01-07
7,8,Tai,Felton,tfelton@umd.edu,890-123-4567,2025-01-08
8,9,Julian,Reece,julianreece@umd.edu,901-234-5678,2025-01-09
9,10,Saylor,Poffenbarger,poffenbarger@umd.edu,012-345-6789,2025-01-10

üîπ Table: sqlite_sequence

          name  seq
0    Customers   10
1    Suppliers   10
2     Products   10
3    Employees   10
4       Orders   10
5  Order_Items   12

üîπ Table: Products

,product_id,name,category,price,stock,supplier_id
0,1,Cricket Bat,Bat,120.0,50,1
1,2,Cricket Ball,Ball,15.0,200,2
2,3,Gloves,Protective Gear,45.0,100,3
3,4,Helmet,Protective Gear,75.0,80,4
4,5,Cricket Pads,Protective Gear,60.0,90,5
5,6,Wicket Keeper Gloves,Protective Gear,50.0,70,6
6,7,Cricket Stumps,Accessories,40.0,60,7
7,8,Cricket Jersey,Apparel,30.0,150,8
8,9,Cricket Shoes,Footwear,85.0,120,9
9,10,Cricket Kit Bag,Accessories,55.0,130,10

üîπ Table: Orders

   order_id  customer_id  employee_id           order_date  total_amount
0         1            1            2  2025-02-10 14:30:00         135.0
1         2            2            3  2025-02-11 15:45:00         180.0
2         3            3            4  2025-02-12 16:00:00          90.0
3         4            4            5  2025-02-13 17:30:00          75.0
4         5            5            1  2025-02-14 18:00:00         120.0
5         6            6            6  2025-02-15 12:00:00         200.0
6         7            7            7  2025-02-16 13:45:00         250.0
7         8            8            8  2025-02-17 14:30:00         300.0
8         9            9            9  2025-02-18 15:15:00         150.0
9        10           10           10  2025-02-19 16:00:00         220.0

üîπ Table: Order_Items

    order_item_id  order_id  product_id  quantity  subtotal
0               1         1           1         2     240.0
1               2         1           3         1      45.0
2               3         2           2         5      75.0
3               4         2           4         1      75.0
4               5         3           5         1      60.0
5               6         4           6         2     100.0
6               7         5           7         1      40.0
7               8         6           8         3      90.0
8               9         7           9         2     170.0
9              10         8          10         1      55.0
10             11         9           2         3      45.0
11             12        10           4         2     150.0

üîπ Table: Employees

,employee_id,first_name,last_name,email,phone_number,role,salary
0,1,Pramod,Kumar,pramod21@terpcricket.com,123-111-2222,Manager,50000.0
1,2,Swati,Nair,swati@terpcricket.com,234-222-3333,Sales Rep,35000.0
2,3,Anirudh,Jayaprakash,ajp@terpcricket.com,345-333-4444,Sales Rep,36000.0
3,4,Bruce,Wayne Jr.,batman@terpcricket.com,456-444-5555,Inventory Manager,40000.0
4,5,Peter,Parker,spideyterp@terpcricket.com,567-555-6666,Cashier,30000.0
5,6,Taylor,Swift,ts@terpcricket.com,678-666-7777,Customer Support,32000.0
6,7,Ryan,Howard,ryan@terpcricket.com,789-777-8888,Marketing,33000.0
7,8,Angela,Martin,angela@terpcricket.com,890-888-9999,Accountant,37000.0
8,9,Anirud,Mohan,am@terpcricket.com,901-999-0000,Finance,38000.0
9,10,Tammy,Perin,tammy@terpcricket.com,012-000-1111,HR,34000.0

üîπ Table: Suppliers

,supplier_id,name,contact_name,phone_number,email,address
0,1,Decathlon,Rajesh Kumar,111-222-3333,raj@indiacricket.com,"Mumbai, India"
1,2,Global Sports,Eoin Morgan,222-333-4444,morgan@globalsports.com,"Los Angeles, USA"
2,3,ProCricket,Arvind Patel,333-444-5555,arvind@procricket.com,"Delhi, India"
3,4,Chennai Sports Hub,Nirav Patel,444-555-6666,nirav@patelbros.com,"Chennai, India"
4,5,SportyTech,Mike Johnson,555-666-7777,mike@sportytech.com,"New York, USA"
5,6,Ultimate Cricket,Rahul Sharma,666-777-8888,rahul@ultimatecricket.com,"Hyderabad, India"
6,7,Cricket Universe,Jessica White,777-888-9999,jessica@cricketuniverse.com,"London, UK"
7,8,Elite Cricket Store,Tom Carter,888-999-0000,tom@elitecricket.com,"Sydney, Australia"
8,9,ProSports,Daniel Green,999-000-1111,daniel@prosports.com,"San Francisco, USA"
9,10,MasterCricket,Vikram Singh,000-111-2222,vikram@mastercricket.com,"Bangalore, India"

## UPDATE

I believe there are two ways in which UPDATES can be performed on SQL.


1.   Either updating one particular attribute of any data
2.   replacing all of that particular data point with a completely new one.

### Method 1: Replacing one or two details of one data point

We will now change the email id, phone number of Lebron James

In [68]:
cur.execute("""
    UPDATE Customers
    SET email = 'kingjames@nba.com', phone_number = '444-321-4901'
    WHERE first_name = 'Lebron' AND last_name = 'James';
""")

con.commit()

# Step 4: Fetch and display updated Customers table
query_after = "SELECT * FROM Customers"
df_after = pd.read_sql_query(query_after, con)

display(df_after)

,customer_id,first_name,last_name,email,phone_number,join_date
0,1,Sachin,Tendulkar,sachintd@gmail.com,123-456-7890,2025-01-01
1,2,MS,Dhoni,mahi7@gmail.com,234-567-8901,2025-01-02
2,3,Aaron,Jones,aaronjones@umd.edu,345-678-9012,2025-01-03
3,4,Virat,Kohli,viratkohli@hotmail.com,456-789-0123,2025-01-04
4,5,Lebron,James,kingjames@nba.com,444-321-4901,2025-01-05
5,6,Kevin,Durrant,kd7@nba.com,678-901-2345,2025-01-06
6,7,Steven,Smith,ssmith@cricketaus.com,789-012-3456,2025-01-07
7,8,Tai,Felton,tfelton@umd.edu,890-123-4567,2025-01-08
8,9,Julian,Reece,julianreece@umd.edu,901-234-5678,2025-01-09
9,10,Saylor,Poffenbarger,poffenbarger@umd.edu,012-345-6789,2025-01-10

It is important to observe that the customer_id does not change.

### Method 2 - Deletion and Insertion

In [69]:
# Step 2: Delete customers with first names "Julian" and "Saylor"
cur.execute("DELETE FROM Customers WHERE first_name IN ('Julian', 'Saylor')")

# Commit the delete operation
con.commit()

# Step 3: Insert new customers Sundar Pichai and Elon Musk
cur.executemany("""
    INSERT INTO Customers (first_name, last_name, email, phone_number, join_date)
    VALUES (?, ?, ?, ?, ?);
""", [
    ("Sundar", "Pichai", "sundar@google.com", "111-222-3333", "2025-02-20"),
    ("Elon", "Musk", "elon@tesla.com", "222-333-4444", "2025-02-21")
])

# Commit the insert operation
con.commit()

# Step 4: Fetch and display updated Customers table
query_after = "SELECT * FROM Customers"
df_after = pd.read_sql_query(query_after, con)

In [70]:
display(df_after)

,customer_id,first_name,last_name,email,phone_number,join_date
0,1,Sachin,Tendulkar,sachintd@gmail.com,123-456-7890,2025-01-01
1,2,MS,Dhoni,mahi7@gmail.com,234-567-8901,2025-01-02
2,3,Aaron,Jones,aaronjones@umd.edu,345-678-9012,2025-01-03
3,4,Virat,Kohli,viratkohli@hotmail.com,456-789-0123,2025-01-04
4,5,Lebron,James,kingjames@nba.com,444-321-4901,2025-01-05
5,6,Kevin,Durrant,kd7@nba.com,678-901-2345,2025-01-06
6,7,Steven,Smith,ssmith@cricketaus.com,789-012-3456,2025-01-07
7,8,Tai,Felton,tfelton@umd.edu,890-123-4567,2025-01-08
8,11,Sundar,Pichai,sundar@google.com,111-222-3333,2025-02-20
9,12,Elon,Musk,elon@tesla.com,222-333-4444,2025-02-21

Look at the customer_id which was created for Sundar and Elon. They are not 9 and 10. Instead, they are 11 and 12.

## Querying

### 1.

In [56]:
drive_path = "/content/drive/My Drive/TerpCricket.db"
if os.path.exists(drive_path):
    os.remove(drive_path)
    print("‚úÖ Database deleted from Google Drive!")

‚úÖ Database deleted from Google Drive!